@echo off
echo.
echo CoffeeScript is BUILDING the .coffee files in the 'templates\js' directory,
echo   compiling them to JavaScript, sending them through Babel,
echo   and outputting .js files to the 'webroot\js' directory.
echo.

rem  First, delete any existing files in the 'webroot' directory,
rem EXCEPT for any read-only files.
@echo off
del /q /s webroot\js\*.js
del /q /s webroot\js\*.map
echo on

rem  My preferred CoffeeScript CLI BUILD command for production:
coffee --compile --no-header --transpile --output webroot\js templates\js

rem  The --no-header option supresses the "Generated by" header
rem  The --transpile option pipes the generated JavaScript through Babel
rem  The --join option is DEPRECATED!

rem  Type "coffee -h" in a terminal for details and more options.

exit /b
