@echo off
echo.
echo CoffeeScript is watching the .coffee files in the 'templates\js' directory,
echo   compiling them to JavaScript, sending them through Babel,
echo   and outputting .js files to the 'webroot\js' directory.
echo.

rem  My preferred CoffeeScript CLI command for development:
coffee --watch --compile --no-header --map --transpile --output webroot\js templates\js

rem  To disable sourcemaps, remove the --map option
rem  The --no-header option supresses the "Generated by" header
rem  The --transpile option pipes the generated JavaScript through Babel

rem  Type "coffee -h" in a terminal for details and more options.

exit
